email: ""
raw_directory: "../../data_NGS" # absolute or relative paths, both are fine
sample_table: "../sample_list/S056_16S.tsv"
outputdir: "../output_S056_16S"
taxonomy:
  mothur:
    do: false
    db_path: "../DBs"
    tax_db: "SILVA_138.1_SSURef_NR99_tax_silva"
  decipher:
    do: true
    db_path: "../DBs/decipher"
    tax_db: "SILVA_SSU_r138_2019.RData"
    db_short_names: "SILVA_SSU_r138_2019"
    look_for_species: true # Does not work with NNNs in unmerged reads with just_concatenate -/ needs some code editing decipher_ID
    spec_db: "../DBs/DADA2/silva_species_assignment_v138.1.fa.gz"
do_primers: true
do_dada: true
do_taxonomy: true
do_postprocessing: true
primers:
# oRM17-18 : 16S-NGS
  fwd:
    sequence: AACGCGAAGAACCTTAC
    name: oRM017_968F_AOS20B
  rvs:
    sequence: TGACGGGCGGTGWGTRCA # primer's own 5'-3' direction
    name: oRM018_1391R_AOS57B
paired: true
sequencing_direction: 'fwd_1'   # "unknown" if the direction is ambiguous/varies across files
filtering:
  trunc_length:
    fwd: 0 #-- ~200-230 ; discards shorter this lengthm hence retains reads with only ends that are bad # default was 0 ; trying arbitrary cutoff
    rvs: 0 # ~ 160 - 230 ; default was 0 ; quality steadily declining, so trying arbitrary cutoff
  trunc_qual:
    fwd: 2 # changed from 16s.yml = 13 -> too high, discarding too many reads, retaining only short ones of 30 bp
    rvs: 2 # "
  max_EE:
    fwd: 4 # August uses 4..; default of 2; changed from 16s.yml of 0.2 - seems too stringent, only 400 sequences are left
    rvs: 4 # " ; 5 was recommended when rvs are poorer - DADA2 tutorial
  # also try trim_left of 10 for both fwd and rev
dada:
    pool: false # default is 'false' -- "pseudo" includes singletons/rare ASVs
blast:  # what is the point of BLAST if taxonomy is being done by other tools?
  do: false     # changed from 16s.yml        # no BLAST database present
  run_basta: false # changed from 16s.yml
pair_merging:
  just_concatenate: false # set to 'true' if reads don't overlap after filtering (only 304 pairs merged out of 80,000)
hand_off:
  biom: true
  phyloseq: false
final_table_filtering:
  do: false # default true;
  keep_target_taxa: "."
  target_min_length: 100 # changed from 245 in 16s.yaml
  target_max_length: 275
postprocessing:
  rarefaction_curve: true # somewhat dubious for DADA2 since singletons are removed as "noise" --
  funguild:
    do: false
  treeing:
    do: true
  tax4fun2:
    do: false # changed from 16s.yml
    user_data: true
