# GENERAL INFORMATION
raw_directory: "/work/$USER"
sample_table: "/work/$USER/samples.tsv"
outputdir: "/work/$USER/output16S_nanoporeChopseq"
# set these

paired: false

email: ""
#  if your system can send emails, it will use this address to notify at the end of a run

# STEPS
do_primers: true
do_dada: true
do_taxonomy: true
do_postprocessing: true
hand_off:
  biom: false
  phyloseq: true
# default output is tsv and RDS; get additional phyloseq object here

# PRIMER REMOVAL SETTINGS
primers:
  fwd: 
    sequence: AGRGTTTGATCMTGGCTCAG
    name: 8F
  rvs:
    sequence: GGGCGGWGTGTACAAG
    name: 1387R
sequencing_direction: "fwd_1"

# READ FILTERING SETTINGS (in DADA2)
filtering:
  trunc_length:
    fwd: 0
  trunc_qual:
    fwd: 0
  max_EE:
    fwd: Inf
  minLen:
    fwd: 1000
  maxLen:
    fwd: Inf
  minQ:
    fwd: 0

# DADA2 SETTINGS
error_seed: 100
dada:
  pool: true
  band_size: 32
  homopolymer_gap_penalty: -1
  use_quals: false
  omega_C: 1
  omega_A: 1e-30
  gapless: false
  no_error_assumptions: false
  errorEstimationFunction: noqualErrfun
  selfConsist: false

chimeras:
  remove: true
  method: poooled
  minFoldParentOverAbundance: 2
  minParentAbundance: 8
  allowOneOff: false
  minOneOffParentDistance: 4
  maxShift: 16

# SETTINGS FOR TAXONOMIC ANNOTATION
taxonomy:
  dada:
    do: false
  decipher:
    do: false
  mothur:
    do: true
    run_on:
      - ASV
      - cluster
    db_path: "../DBs/mothur"
    tax_db: "SILVA_138_SSURef_NR99_prok"
    db_short_names: "SILVA_138_SSURef_NR99"
    cutoff: 60
# set these paths!
    
blast:
  do: true
  run_on:
    - ASV
    - cluster
  db_path: "../DBs/ncbi_16S_ribosomal_RNA"
  tax_db: 16S_ribosomal_RNA
  all: true
  run_basta: true
  basta_db: "../DBs/ncbi_taxonomy"
# set these paths!

# SETTINGS FOR CLUSTERING ASV TABLE AT e.g. 97%
post_clustering:
  do: true
  cutoff: 0.97
# I've never tested this

# SETTINGS FOR POST-PROCESSING
final_table_filtering:
  do: true
  keep_target_taxa: "."
  target_min_length: 1000
  target_max_length: 2000
postprocessing:
  rarefaction_curve: true
  picrust2:
    do: true
    stratified: true
    max_nsti: 2
  treeing:
    do: true
