email: ""
sessionName: ""
normalMem: ""
bigMem: ""
bigCores: ""
sessionKind: ""
settingsLocked: false
big_data: false
tmp_dir: "tmp"
raw_directory: "testdata"
sample_table: "testdata/samples.small.tsv"
do_primers: true
do_dada: true
do_taxonomy: true
do_postprocessing: true
primers:
  fwd: 
    sequence: GTGYCAGCMGCCGCGGTAA
    name: 515F
  rvs: 
    sequence: GGACTACNVGGGTWTCTAAT
    name: 806R
paired: true
sequencing_direction: "unknown"
primer_cutting:
  overlap: 10
  count: 2
  filter_if_not_match: any
  perc_mismatch: 0.2
  indels: "--no-indels"
  both_primers_in_read: false
filtering:
  trunc_length:
    fwd: 0
    rvs: 0
  trunc_qual: 
    fwd: 2
    rvs: 2
  max_EE:
    fwd: Inf
    rvs: Inf
  minLen:
    fwd: 20
    rvs: 20
  maxLen:
    fwd: Inf
    rvs: Inf
  minQ:
    fwd: 0
    rvs: 0
  maxN: 0
  rm_phix: true
  trim_left:
    fwd: 0
    rvs: 0
downsampling:
  do: false
  number: 50000
  min: true
  seed: 123
error_seed: 100
dada:
  band_size: 16
  homopolymer_gap_penalty: NULL
  pool: false
  omega_A: 1e-40
  priors: ""
  omega_P: 1e-4
  omega_C: 1e-40
  gapless: true
  selfConsist: false
  no_error_assumptions: false
  kdist_cutoff: 0.42
  match: 4
  mismatch: -5
  gap_penalty: -8
  errorEstimationFunction: loessErrfun
  use_quals: true
pair_merging:
  min_overlap: 12
  max_mismatch: 0
  just_concatenate: false
  trim_overhang: true
chimeras:
  remove: true
  remove_by_run: false
  method: consensus
  minFoldParentOverAbundance: 2
  minParentAbundance: 8
  allowOneOff: false
  minOneOffParentDistance: 4
  maxShift: 16
outputdir: "dadasnake_output"
taxonomy:
  dada:
    do: false
    post_ITSx: false
    db_path: "../DBs/DADA2"
    refFasta: "silva_nr99_v138_train_set.fa.gz"
    ref_dbs_full: ""
    db_short_names: "silva_v138_nr99"
    minBoot: 50 
    tryRC: false
    look_for_species: false
    seed: 101
    spec_db: "../DBs/DADA2/silva_species_assignment_v138.fa.gz"
  decipher:
    do: false
    post_ITSx: false
    db_path: "../DBs/decipher"
    tax_db: "SILVA_SSU_r138_2019.RData"
    ref_dbs_full: ""
    db_short_names: "SILVA_SSU_r138"
    threshold: 60
    strand: top
    bootstraps: 100
    seed: 100  
    look_for_species: false
    spec_db: "../DBs/DADA2/silva_species_assignment_v138.fa.gz"
  mothur:
    do: true
    post_ITSx: false
    db_path: "../DBs/mothur"
    tax_db: "SILVA_138_SSURef_NR99_prok.515F.806R"
    ref_dbs_full: ""
    db_short_names: "SILVA_138_SSURef_NR99_cut"
    cutoff: 60
    rank_number: 7
blast:
  do: false
  db_path: "../DBs/ncbi_16SMicrobial"
  tax_db: 16S_ribosomal_RNA
  e_val: 0.01
  tax2id: ""
  all: true
  max_targets: 10
  run_basta: false
  basta_path: "../bin/basta"
  basta_db: "../DBs/ncbi_taxonomy"
  basta_e_val: 0.00001
  basta_alen: 100
  basta_number: 0
  basta_min: 3
  basta_id: 80
  basta_besthit: true
  basta_perchits: 99
ITSx:
  do: false
  min_regions: 1
  region: ITS2
  e_val: 1e-5
  query_taxa: .
  target_taxon: F
hand_off:
  biom: true
  phyloseq: false
final_table_filtering:
  do: true
  keep_target_taxa: "."
  target_min_length: 1
  target_max_length: 10000
postprocessing:
  rarefaction_curve: true
  funguild:
    do: false
    funguild_db: "../DBs/functions/funguild_db.json"
    classifier: mothur
  fungalTraits:
    do: false
    db: "../DBs/functions/FungalTraits_1.2_ver_16Dec_2020_V.1.2.tsv"
    classifier: mothur.SILVA_138_SSURef_NR99_cut
  tax4fun2:
    do: false
    db: "../DBs/Functions/Tax4Fun2_ReferenceData_v2"
    database_mode: "Ref99NR"
    normalize_by_copy_number: true 
    min_identity_to_reference: 0.97
    user_data: false
    user_dir: "../DBs/Functions/GTDB_202_tax4fun2"
    user_db: "GTDB_fun"
  treeing:
    do: true
    fasttreeMP: ""
